= Community site REST API
최동혁;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-http-request-title: Request
:operation-http-response-title: Response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리함

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 `Location` 헤더에 해당 리소스의 URI가 담겨있다.

| `400 Bad Request`
| 잘못된 요청을 보낸 경우. 응답 본문에 더 오류에 대한 정보가 담겨있다.

| `404 Not Found`
| 요청한 리소스가 없음.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때, 본문에 해당 문제를 기술한 JSON 객체가 담겨있다. 에러 객체는 다음의 구조를 따른다.

operation::create-Account-Errors[snippets='http-request']

예를 들어, 잘못된 요청으로 이벤트를 만들려고 했을 때 다음과 같은 `400 Bad Request` 응답을 받는다.

operation::create-Account-Errors[snippets='http-response']

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

[[resources-account]]
== Account

Account 생성, 삭제, 조회, 수정 작업을 제공한다.

[[resources-account-create]]
=== Create Account

`POST` 요청을 이용하여 Form 값을 전달하면 Account를 생성이 된다.

operation::create-Account[snippets='http-request,http-response,links']

[[resources-account-get]]
=== Read Account

`GET` 요청을 이용하면 해당하는 Account의 값을 받아올 수 있다.

operation::get-Account[snippets='curl-request,http-response,links']

[[resources-account-update]]
=== Update Account

`PUT` 요청을 이용하여 Form 값을 전달하면 그 값으로 수정이 된다.

operation::update-Account[snippets='http-request,http-response,links']

[[resources-account-delete]]
=== Delete Account

`DELETE` 요청을 이용하여 Account를 삭제할 수 있다.

operation::delete-Account[snippets='http-request,http-response']

[[resources-Account-article]]
== Account's Article

특정 Account의 Article 생성, 삭제, 조회 수정 작업을 제공한다.

[[resources-Account-article-create]]
=== Create Article

`POST` 요청을 이용하여 Form 값을 전달하면 Account를 생성이 된다.

[[resources-Account-article-get]]
=== Read Article

`GET` 요청을 이용하면 해당하는 Article의 값을 받아올 수 있다.

operation::get-Account-Article[snippets='curl-request,http-response,links']

[[resources-Account-article-update]]
=== Update Article

`PUT` 요청을 이용하여 Form 값을 전달하면 그 값으로 수정이 된다.

[[resources-Account-article-delete]]
=== Delete Article

`DELETE` 요청을 이용하여 Article을 삭제할 수 있다.

operation::delete-Account-Article[snippets='curl-request,http-response']

