= Community site REST API
최동혁;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-http-request-title: Request
:operation-http-response-title: Response

[[overview]]
= 개요

[[overview-http-verbs]]
== HTTP 동사

본 REST API에서 사용하는 HTTP 동사(verbs)는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 동사 | 용례

| `GET`
| 리소스를 가져올 때 사용

| `POST`
| 새 리소스를 만들 때 사용

| `PUT`
| 기존 리소스를 수정할 때 사용

| `DELETE`
| 기존 리소스를 삭제할 떄 사용
|===

[[overview-http-status-codes]]
== HTTP 상태 코드

본 REST API에서 사용하는 HTTP 상태 코드는 가능한한 표준 HTTP와 REST 규약을 따릅니다.

|===
| 상태 코드 | 용례

| `200 OK`
| 요청을 성공적으로 처리한다.

| `201 Created`
| 새 리소스를 성공적으로 생성함. 응답의 Body의 link로 다음 동작을 유추할 수 있다.

| `400 Bad Request`
| URL 요청에서의 잘못된 요청, 혹은 Form 값의 부재 등의 이유일 경우 처리, Form 값의 부재인 경우 Error 메시지가 첨부 되지만 URL의 잘못된 요청인 경우 첨부되지 않는다.

| `403 ForBidden`
| Request 요청 시 로그인이 되어 있지 않은 경우 접근 권한 부족의 에러로써의 의미로 처리한다.

| `404 Not Found`
| 요청한 리소스를 찾을 수 없다.
|===

[[overview-errors]]
== 오류

에러 응답이 발생했을 때, 본문에 해당 문제를 기술한 JSON 객체가 담겨있다. 에러 객체는 다음의 구조를 따른다.

operation::create-Account-Errors[snippets='curl-request']

예를 들어, 잘못된 요청으로 이벤트를 만들려고 했을 때 다음과 같은 `400 Bad Request` 응답을 받는다.

operation::create-Account-Errors[snippets='http-response']

[[overview-hypermedia]]
== 하이퍼미디어

본 REST API는 하이퍼미디어와 사용하며 응답에 담겨있는 리소스는 다른 리소스에 대한 링크를 가지고 있다.
응답은 http://stateless.co/hal_specification.html[Hypertext Application from resource to resource. Language (HAL)] 형식을 따른다.
링크는 `_links`라는 키로 제공한다. 본 API의 사용자(클라이언트)는 URI를 직접 생성하지 않아야 하며, 리소스에서 제공하는 링크를 사용해야 한다.

[[resources]]
= 리소스

모든 요청은 Application/JSON 타입을 받으며, 응답은 HAL_JSON 타입의 응답을 한다.
또한 접근 권한에 따라 로그인 여부를 확인하는데, 이 때 https://jwt.io/[JWT] 방식을 사용한다.

[[resources-account]]
== Account

Account 생성, 삭제, 조회, 수정 작업을 제공한다.

[[resources-account-get]]
=== Read Account

`GET` 요청을 이용하면 해당하는 Account의 값을 받아올 수 있다.

operation::get-Account[snippets='curl-request,http-response,response-fields,links']

[[resources-account-create]]
=== Create Account

`POST` 요청을 이용하여 Form 값을 전달하면 Account를 생성이 된다.

operation::create-Account[snippets='curl-request,request-fields,http-response,links']

[[resources-account-update]]
=== Update Account

`PUT` 요청을 이용하여 Form 값을 전달하면 그 값으로 수정이 된다.

operation::update-Account[snippets='curl-request,request-fields,http-response,links']

[[resources-account-delete]]
=== Delete Account

`DELETE` 요청을 이용하여 Account를 삭제할 수 있다.

operation::delete-Account[snippets='curl-request,request-fields,http-response,response-headers']

[[resources-Account-article]]
== Account's Article

특정 Account의 Article 생성, 삭제, 조회 수정 작업을 제공한다.

[[resources-Account-article-get]]
=== Read Article

`GET` 요청을 이용하면 해당하는 Article의 값을 받아올 수 있다.

operation::get-Account-Article[snippets='curl-request,http-response,response-fields-beneath-_embedded.articleDTOList,response-fields-beneath-page,links']

[[resources-Account-article-delete]]
=== Delete Article

`DELETE` 요청을 이용하여 Article을 삭제할 수 있다.

operation::delete-Account-Article[snippets='curl-request,request-headers,http-response,response-headers']

[[resources-Account-comments]]
== Account's Comments

특정 Account의 Comments 생성, 삭제, 조회 수정 작업을 제공한다.

[[resources-Account-comments-get]]
=== Read Comments

`GET` 요청을 이용하면 해당하는 Comments의 값을 받아올 수 있다.

operation::get-Account-Comments[snippets='curl-request,http-response,response-fields-beneath-_embedded.commentsDTOList,response-fields-beneath-page,links']

[[resources-Account-comments-delete]]
=== Delete Comments

`DELETE` 요청을 이용하여 Comments을 삭제할 수 있다.

operation::delete-Account-Comments[snippets='curl-request,request-headers,http-response,response-headers']

[[resources-Account-notification]]
== Account's Notification

특정 Account의 Comments 생성, 삭제, 조회 수정 작업을 제공한다.

[[resources-Account-notification-get]]
=== Read Notification

`GET` 요청을 이용하면 해당하는 Notification의 값을 받아올 수 있다.

operation::get-Account-Notification[snippets='curl-request,http-response,response-fields-beneath-_embedded.notificationDTOList,response-fields-beneath-page,links']

[[resources-Account-notification-delete]]
=== Delete Notification

`DELETE` 요청을 이용하여 Notification을 삭제할 수 있다.

operation::delete-Account-Notification[snippets='curl-request,request-headers,http-response,response-headers']

[[resources-Community]]
== Community

Community 생성, 삭제, 조회, 수정 작업을 제공한다.

[[resources-Community-get]]
=== Read Community

`GET` 요청을 이용하면 해당하는 Community의 게시판을 보여주며 이에 속해있는 Article들을 보여준다.

operation::get-Community-Article[snippets='curl-request,http-response,response-fields-beneath-_embedded.articleDTOList,response-fields-beneath-page,links']

[[resources-Community-get-WithType]]
=== Read CommunityWithType

게시글의 Type별로 받아보고 싶다면 이와 같이 사용한다.

operation::get-Community-ArticleWithType[snippets='curl-request,request-headers,http-response,links']

[[resources-Community-create]]
=== Create Community

`POST` 요청을 이용하여 Form 값을 전달하면 Community가 생성이 된다. 이 기능은 권한을 가지고 있는 자만 사용이 가능하다.

operation::create-Community[snippets='curl-request,request-fields,http-response,links']

[[resources-Community-update]]
=== Update Community

`PUT` 요청을 이용하여 Form 값을 전달하면 그 값으로 수정이 된다.

operation::update-Account[snippets='curl-request,request-fields,http-response,links']

[[resources-Community-delete]]
=== Delete Community

`DELETE` 요청을 이용하여 Community를 삭제할 수 있다.

operation::delete-Account[snippets='curl-request,http-response,response-headers']

[[resources-Community-Article]]
== Community' Article

Community안의 게시글을 생성, 삭제, 조회, 수정 작업을 제공한다.

[[resources-Community-Article-get]]
=== Read Community' Article

`GET` 요청을 이용하면 해당하는 Community의 게시판을 보여주며 이에 속해있는 Article들과 Comments들을 보여준다.

operation::get-Community-Article[snippets='curl-request,http-response,response-fields-beneath-_embedded.articleDTOList,links']

[[resources-Community-Article-create]]
=== Create Community's Article

`POST` 요청을 이용하여 Form 값을 전달하면 Article이 생성이 된다.

operation::create-Community-Article[snippets='curl-request,request-fields,http-response,links']

[[resources-Community-Article-updatePage]]
=== Read Community's Article Update Page

`GET` 요청을 이용하여 수정을 원하는 Article의 정보를 획득할 수 있다.

operation::get-Community-Article-modify[snippets='curl-request,http-response,response-fields,links']

[[resources-Community-Article-update]]
=== Update Community's Article

`PUT` 요청을 이용하여 Form 값을 전달하면 그 값으로 수정이 된다.

operation::update-Community-Article[snippets='curl-request,request-fields,http-response,links']

[[resources-Community-Article-delete]]
=== Delete Community

`DELETE` 요청을 이용하여 게시글을 삭제할 수 있다.

operation::delete-Community-Article[snippets='curl-request,http-response,response-headers']

//
[[resources-Article-Comments]]
== Article's Comments

Article의 Comments를 생성, 삭제, 조회, 수정 작업을 제공한다.

[[resources-Article-Comments-create]]
=== Create Article's Comments

`POST` 요청을 이용하여 Form 값을 전달하면 Comments가 생성이 된다.

operation::create-Article-Comments[snippets='curl-request,request-fields,http-response,links']

[[resources-Article-Comments-update]]
=== Update Article's Comments

`PUT` 요청을 이용하여 Form 값을 전달하면 그 값으로 수정이 된다.

operation::update-Article-Comments[snippets='curl-request,request-fields,http-response,links']

[[resources-Article-Comments-delete]]
=== Delete Article's Comments

`DELETE` 요청을 이용하여 게시글을 삭제할 수 있다.

operation::delete-Community-Article[snippets='curl-request,http-response,response-headers']